// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"Personal/micro-skeleton/internal/api"
	"Personal/micro-skeleton/internal/api/grpc"
	"Personal/micro-skeleton/internal/commands"
	"Personal/micro-skeleton/internal/config"
	"Personal/micro-skeleton/internal/db"
	"Personal/micro-skeleton/internal/handlers"
	"Personal/micro-skeleton/internal/repo"
)

// Injectors from wire.go:

func ConfigureServer() *api.Server {
	configConfig := config.NewConfig()
	getItem := handlers.NewGetItemHandler()
	conn := db.NewDBConnection()
	itemsRepo := repo.NewItemsRepo(conn)
	inventoryManager := commands.NewInventoryManager(itemsRepo)
	createItem := handlers.NewCreateItemHandler(inventoryManager)
	updateItem := handlers.NewUpdateItemHandler()
	mux := api.NewRouter(getItem, createItem, updateItem)
	server := grpc.NewServer(inventoryManager)
	apiServer := api.NewServer(configConfig, mux, server)
	return apiServer
}
