// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"Personal/micro-skeleton/internal/api"
	"Personal/micro-skeleton/internal/config"
)

// Injectors from wire.go:

func ConfigureServer() *api.Server {
	configConfig := config.NewConfig()
	mux := api.NewRouter()
	server := api.NewServer(configConfig, mux)
	return server
}
