// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/api/grpc/skeleton.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       *string `protobuf:"bytes,1,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price    float32 `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Count    *int32  `protobuf:"varint,4,opt,name=Count,proto3,oneof" json:"Count,omitempty"`
	ImageURL *string `protobuf:"bytes,5,opt,name=ImageURL,proto3,oneof" json:"ImageURL,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_skeleton_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_skeleton_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_skeleton_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *Item) GetImageURL() string {
	if x != nil && x.ImageURL != nil {
		return *x.ImageURL
	}
	return ""
}

type ItemID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ItemID) Reset() {
	*x = ItemID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_skeleton_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemID) ProtoMessage() {}

func (x *ItemID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_skeleton_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemID.ProtoReflect.Descriptor instead.
func (*ItemID) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_skeleton_proto_rawDescGZIP(), []int{1}
}

func (x *ItemID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_internal_api_grpc_skeleton_proto protoreflect.FileDescriptor

var file_internal_api_grpc_skeleton_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f,
	0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x13, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x52, 0x4c, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x49, 0x44, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x52, 0x4c, 0x22, 0x18, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x32, 0x82, 0x01,
	0x0a, 0x0d, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x53, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x13, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x1a, 0x13, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74,
	0x6f, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6b, 0x65, 0x6c,
	0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x1a, 0x13, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x6b, 0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_api_grpc_skeleton_proto_rawDescOnce sync.Once
	file_internal_api_grpc_skeleton_proto_rawDescData = file_internal_api_grpc_skeleton_proto_rawDesc
)

func file_internal_api_grpc_skeleton_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_skeleton_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_skeleton_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_grpc_skeleton_proto_rawDescData)
	})
	return file_internal_api_grpc_skeleton_proto_rawDescData
}

var file_internal_api_grpc_skeleton_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_grpc_skeleton_proto_goTypes = []interface{}{
	(*Item)(nil),   // 0: microskeleton.Item
	(*ItemID)(nil), // 1: microskeleton.ItemID
}
var file_internal_api_grpc_skeleton_proto_depIdxs = []int32{
	0, // 0: microskeleton.MicroSkeleton.CreateItem:input_type -> microskeleton.Item
	1, // 1: microskeleton.MicroSkeleton.GetItem:input_type -> microskeleton.ItemID
	0, // 2: microskeleton.MicroSkeleton.CreateItem:output_type -> microskeleton.Item
	0, // 3: microskeleton.MicroSkeleton.GetItem:output_type -> microskeleton.Item
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_skeleton_proto_init() }
func file_internal_api_grpc_skeleton_proto_init() {
	if File_internal_api_grpc_skeleton_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_grpc_skeleton_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_grpc_skeleton_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_api_grpc_skeleton_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_grpc_skeleton_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_skeleton_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_skeleton_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_skeleton_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_skeleton_proto = out.File
	file_internal_api_grpc_skeleton_proto_rawDesc = nil
	file_internal_api_grpc_skeleton_proto_goTypes = nil
	file_internal_api_grpc_skeleton_proto_depIdxs = nil
}
